apiVersion: v1
kind: Secret
metadata:
  name: trading-secrets
type: Opaque
data:
  DATABASE_URL: {{ "postgresql://user:pass@db:5432/trading_db" | b64enc }}
  EMAIL_HOST: {{ "smtp.example.com" | b64enc }}
  EMAIL_PORT: {{ "587" | b64enc }}
  EMAIL_USER: {{ "user@example.com" | b64enc }}
  EMAIL_PASS: {{ "secret" | b64enc }}
  SLACK_WEBHOOK_URL: {{ "https://hooks.slack.com/… " | b64enc }}
  METRICS_PUSHGATEWAY: {{ "http://pushgateway:9091" | b64enc }}
