apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "daily-trader.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python","-m","src.main"]
            envFrom:
            - secretRef:
                name: {{ include "daily-trader.fullname" . }}-secrets
          restartPolicy: OnFailure
