apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daily-trader.fullname" . }}-secrets
type: Opaque
data:
  DATABASE_URL:         {{ .Values.secrets.databaseUrl     | b64enc }}
  EMAIL_HOST:           {{ .Values.secrets.email.host      | b64enc }}
  EMAIL_PORT:           {{ .Values.secrets.email.port      | quote | b64enc }}
  EMAIL_USER:           {{ .Values.secrets.email.user      | b64enc }}
  EMAIL_PASS:           {{ .Values.secrets.email.pass      | b64enc }}
  SLACK_WEBHOOK_URL:    {{ .Values.secrets.slackWebhookUrl | b64enc }}
  METRICS_PUSHGATEWAY:  {{ .Values.secrets.pushgateway     | b64enc }}
